apiVersion: apps/v1
kind: Service
metadata:
  name: simple-python-app-service
spec:
  selector:
    app: simple-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
